# This would normally be ~/.ecscmd.toml
[taskdef.test]
family = "testTaskDef"
template = "samples/taskDefTemplate.json"
[taskdef.test.templatevars]
ExecutionRoleArn = "arn:aws:iam::12345678:role/ecsTaskExecutionRole"
ContainerName = "foo"
Image = "mydockerimage"
DjangoSettingsModule = "myapp.settings.production"
Command = "/run_my_app.sh"
[service.sample]
name = "A-Service"
